# Generated by Django 5.2.8 on 2025-12-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='fee',
            field=models.FloatField(default=0),
        ),
    ]
