# Generated by Django 5.2.8 on 2025-12-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_parkingsession_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslots',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
