# Generated by Django 5.2.8 on 2025-12-05 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_parkingslots_is_reserved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('owner_name', models.CharField(max_length=50)),
                ('hours', models.IntegerField()),
                ('vehicle_type', models.CharField(max_length=20)),
                ('reserve_time', models.DateTimeField(auto_now_add=True)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.parkingslots')),
            ],
        ),
    ]
